checks:
  php: true

filter:
  excluded_paths:
    - 'tests/'

build:
  environment:
    # Languages
    php:
      version: "7.4"

  tests:
    override:
      -
        command: 'vendor/bin/phpunit'
        coverage:
            file: 'build/coverage-phpunit/clover.xml'
            format: 'clover'
      - php-scrutinizer-run
